### PR TITLE
Allow skipping certain struct fields while fuzzing (based on a specified prefix)

### PR DESCRIPTION
**Pull request by samirkut**
Protobuf generated code have certain exported fields (XXX_...) which cannot be set as that corrupts the serialization. This change allows specifying certain prefix for fields which are ignored while fuzzing a struct.

### CODE REVIEW

**Comment by samirkut** [comment]
@googlebot I signed it!

**Comment by lavalamp** [comment]
I think this is a pretty reasonable feature to have, but what do you think about making it a regexp match rather than a prefix match?

I'm just imagining in the future someone wanting a regexp match-- then it would feel a little silly to have both, but that would also be a reasonable thing to ask for.

**Comment by lavalamp** [comment]
Also, this needs a test. :)

**Comment by samirkut** [comment]
You are right. Regex makes it a bit more flexible. Updated (with tests)

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks! I almost nitpicked about the name, but I don't think I have a suggestion that's a clear improvement, so LGTM :)

**Comment by lavalamp** [comment]
Oh I forgot this isn't a kubernetes repo, just a second...

**Pull request merged**
