### PR TITLE
Seed the fuzzer in tests

### PR DESCRIPTION
**Pull request by punkeel**
The tests are slightly flakey as they rely on randomness. Setting a constant seed will help stabilize them.

### CODE REVIEW

**Comment by lavalamp** [comment]
Sorry I missed this in my email when you opened it, I'll try to take a look soon.

**Comment by dnephin** [comment]
I took another approach in #52 which adjusts some of the values instead of seeding. I guess it won't be as reliable as this approach, but it might be nice to keep some of the randomness so that tests don't accidentally pass because of one seeded value.

**Comment by lavalamp** [comment]
@punkeel thanks for sending this and I'm sorry I never properly reviewed, I think I do slightly prefer the approach in #52, mostly because it might be frustrating to search for a "good" seed if one changes something (though admittedly, in practice, it's kind of a weak reason since your seeds look like you didn't have to do too much searching); a better reason is that omitting a seed makes a stronger statement about the code under test (but this doesn't motivate me as much).

**Comment by punkeel** [comment]
No worries! :-)

**Pull request closed without merging**
