### PR TITLE
Support fuzzing array values

### PR DESCRIPTION
**Pull request by korya**
The commit adds the support for fuzzing array values

### CODE REVIEW

**Comment by korya** [comment]
I signed it!

**Comment by korya** [comment]
Hey guys, do you have any comments or objections to the PR? It would be great to merge it ASAP, since it's blocking https://github.com/pquerna/ffjson/pull/160.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Thanks!

**Comment by korya** [comment]
Thanks!

**Pull request merged**
